### ISSUE TITLE
password

### ISSUE THREAD

**Issue by 1x6** [GiriAakula/torrent-streamer#1]
u left ur password in there, might wanna remove it?

![opera_8neosUVWSX](https://user-images.githubusercontent.com/44981148/166523055-b64a02a1-0022-42bc-bf62-2ce03479a084.png)
![opera_JUis7jmk5K](https://user-images.githubusercontent.com/44981148/166523106-db1c7b8b-fedc-4bef-80c5-51111686c780.png)

**Comment by GiriAakula** [comment]
Thank you for pointing that. It was supposed to be an easter egg, obviously it is not as you found it.
